### PR TITLE
Minimize README

### PR DESCRIPTION
**Pull request by aachh**
just a break-up, the "commands" section will be in `COMMANDS.md` (#13)

### CODE REVIEW

**Comment by aachh** [comment]
done, glad I could contribute! 😄

**Comment by wintondeshong** [comment]
@aachh sorry if I'm overlooking it, but don't see another commit in this branch

**Comment by aachh** [comment]
@wintondeshong tbh I'm not sure what you meant by "updating the document," I just edited the PR description

**Comment by wintondeshong** [comment]
@aachh Ah, I see the confusion. Sorry about that! Could you add a link from README.md to COMMANDS.md?

**Comment by aachh** [comment]
Oh gosh, I'm such a dummy. Doing it now 😅

**Comment by wintondeshong** [comment]
Thanks for buttoning that up @aachh 👍

**Pull request merged**
